### ISSUE TITLE
composer install fails

### ISSUE THREAD

**Issue by elstamey** [lazychaser/nestedset-app#1]
When I run `composer install`, it fails because it cannot find the repository url for boris.  

Can you please make a recommendation whether it be updating the composer.json file or removing the url from the repositiories section?  

Thank you,
Emily
## (pasted the results below)

$ composer install
Loading composer repositories with package information
Your GitHub credentials are required to fetch private repository metadata (https://github.com/laravel/boris)
The credentials will be swapped for an OAuth token stored in /Users/elstamey/.composer/config.json, your password will not be stored
To revoke access to this token you can visit https://github.com/settings/applications
Username: elstamey
Password: 

  [Composer\Downloader\TransportException]  
  The "https://api.github.com/repos/laravel/boris" file could not be downloaded (HTTP/1.1 404 Not Found)  

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader]

**Comment by lazychaser** [comment]
Yeah, original Laravel app removed this custom dependency. Updated composer.json.

**Comment by elstamey** [comment]
thanks!
