### ISSUE TITLE
ErrorException: Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by mdwheele** [lazychaser/nestedset-app#2]
I receive the following error out of the box.  When I prevent the PageController from instantiating the layout member variable, all works fine... 

I don't think that's the solution, but I don't have time (at the moment) to debug any further.  When I get home tonight, I'll try to get more details on why the layout is causing issues.  My off-the-cuff is that there is a configuration issue in pathing preventing Blade inheritance from working properly, but that's not entirely grounded...

Error I'm getting:
![image](https://f.cloud.github.com/assets/2453394/1883142/55ed1ffe-7981-11e3-8bb5-0cccb9350a82.png)

https://github.com/lazychaser/nestedset-app/blob/master/app/controllers/PageController.php
https://github.com/lazychaser/nestedset-app/blob/master/app/controllers/BaseController.php

Code for "band-aid fix":

```
    public function __construct(Page $page, MarkdownParser $markdown)
    {
        $this->page = $page;
        $this->markdown = $markdown;

        //$this->setupLayout();
    }
```

**Comment by mdwheele** [comment]
Added links to relevant source.  As an aside, I really appreciate the work on nestedset itself.  I'm looking forward to using and contributing in a project coming up very soon.  I never have to mess with nested tediousness again! :+1:

**Comment by lazychaser** [comment]
Thanks for the feedback! I've updated the repo.
