### ISSUE TITLE
App crashes when updating

### ISSUE THREAD

**Issue by ava7** [lazychaser/nestedset-app#3]
Hello Kalnoy,

The app crashes when one choose to set the parent of a page to itself (query error).

If I could be any help of you, here is my solution for it. I used a single if statement that checks whether the submitted parent_id matches the id of the page. If so, I trigger a method that adds the parent_id field into the guarded array of the model.

Before validating and using the fill method:

```
if (Input::get('parent_id') == $page->id) {
    $page->setGuarded(array('parent_id'));          
}
```

And for the model:

```
class Page extends \Kalnoy\Nestedset\Node {
    protected $guarded = array();

    public function setGuarded($guarded = array()) {
        foreach ($guarded as $v) {
            $this->guarded[] = $v;
        }
    }
    // ...
}
```

Cheers!

**Comment by lazychaser** [comment]
I have updated the repository to display the error as an error rather than an exception. Also made some refactoring and additions, so do a composer update.
